#!/usr/bin/env node
/**
 * build-skills.mjs — make the plugin skills the SINGLE SOURCE OF TRUTH for the
 * web assistant.
 *
 * Reads `../plugin/skills/<slug>/SKILL.md` (+ references/ + assets/) and emits
 * `web/lib/ai/skills.generated.ts`, embedding every skill body and reference as
 * a string constant. `systemPrompt.ts` assembles SYSTEM_PROMPT from the bodies;
 * the `get_skill_reference` action serves the references on demand.
 *
 * Round-1 (Architecture D): the generator is split into a PURE function —
 * `generateSkillsSource()` — importable by tests, and the CLI wrapper below is
 * the ONLY writer of `web/lib/ai/skills.generated.ts`. Tests assert
 * source-to-generated equality under the generator's REAL normalization and
 * that two builds produce identical bytes. The plugin skills stay the editable
 * truth; the generated module is generated-only (never hand-edited).
 *
 * Run: `npm run build:skills`
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { dirname, join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';

const HERE = dirname(fileURLToPath(import.meta.url));
const SKILLS_DIR = join(HERE, '..', '..', 'plugin', 'skills');
const OUT = join(HERE, '..', 'lib', 'ai', 'skills.generated.ts');

/** Hub first, then spokes — the order they are inlined into SYSTEM_PROMPT. */
const ORDER = [
  'managing-clash-config',
  'synthesizing-proxy-groups',
  'editing-node-operators',
  'managing-devices',
  'optimizing-whole-config',
];

function splitFrontmatter(text) {
  const m = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/.exec(text);
  if (!m) return { frontmatter: '', body: text.trim() };
  return { frontmatter: m[1], body: m[2].trim() };
}

function fieldName(fm) {
  const m = /^name:\s*(\S+)/m.exec(fm);
  return m ? m[1].trim() : '';
}

function fieldDescription(fm) {
  // block scalar `description: >-` followed by indented lines
  const block = /^description:\s*>-?\s*\n((?:[ \t]+.*\n?)+)/m.exec(fm);
  if (block)
    return block[1]
      .split('\n')
      .map((l) => l.trim())
      .filter(Boolean)
      .join(' ');
  const inline = /^description:\s*(.+)$/m.exec(fm);
  return inline ? inline[1].trim() : '';
}

function readDirMd(dir) {
  if (!existsSync(dir) || !statSync(dir).isDirectory()) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .map((f) => ({ name: basename(f, '.md'), body: readFileSync(join(dir, f), 'utf8').trim() }));
}

/** Pure load: skill bodies + references + order (no writes, no formatting). */
export function loadSkills(options = {}) {
  const skillsDir = options.skillsDir ?? SKILLS_DIR;
  const order = options.order ?? ORDER;
  const bodies = {};
  const references = {};
  for (const slug of order) {
    const skillDir = join(skillsDir, slug);
    const skillFile = join(skillDir, 'SKILL.md');
    if (!existsSync(skillFile)) {
      throw new Error(`[build-skills] MISSING ${skillFile}`);
    }
    const { frontmatter, body } = splitFrontmatter(readFileSync(skillFile, 'utf8'));
    bodies[slug] = {
      name: fieldName(frontmatter) || slug,
      description: fieldDescription(frontmatter),
      body,
    };
    // references/ + assets/ → key `<slug>/<file>`
    for (const sub of ['references', 'assets']) {
      for (const ref of readDirMd(join(skillDir, sub))) {
        references[`${slug}/${ref.name}`] = ref.body;
      }
    }
  }
  return { bodies, references, order };
}

const header = `// GENERATED by scripts/build-skills.mjs from ../plugin/skills — DO NOT EDIT BY HAND.
// Regenerate after editing any SKILL.md / reference: \`npm run build:skills\`.
// The plugin skills are the single source of truth; this module embeds them so
// the web app ships self-contained (no runtime access to the repo-root plugin/).

export interface SkillBody {
  name: string;
  description: string;
  body: string;
}

`;

/**
 * PURE generator: returns the EXACT TypeScript source `build:skills` writes to
 * web/lib/ai/skills.generated.ts, under the generator's real normalization
 * (same skill loading + same prettier formatting). Tests import this and
 * assert source-to-generated equality and byte-determinism.
 */
export async function generateSkillsSource(options = {}) {
  const { bodies, references, order } = loadSkills(options);
  const out =
    header +
    `export const SKILL_ORDER: readonly string[] = ${JSON.stringify(order)};\n\n` +
    `export const SKILL_BODIES: Record<string, SkillBody> = ${JSON.stringify(bodies, null, 2)};\n\n` +
    `/** Reference / asset bodies keyed as \`<skill-slug>/<file-without-.md>\`. */\n` +
    `export const SKILL_REFERENCES: Record<string, string> = ${JSON.stringify(references, null, 2)};\n`;
  const prettierConfig = (await resolveConfig(options.outFile ?? OUT)) ?? {};
  return format(out, { ...prettierConfig, filepath: options.outFile ?? OUT });
}

/** CLI wrapper — the ONLY writer of skills.generated.ts. */
async function main() {
  const source = await generateSkillsSource();
  writeFileSync(OUT, source);
  const { bodies, references } = loadSkills();
  console.error(
    `[build-skills] wrote ${OUT}\n  skills: ${Object.keys(bodies).length}  references: ${Object.keys(references).length}`,
  );
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
