#!/usr/bin/env node
/**
 * build-skills.mjs — make the plugin skills the SINGLE SOURCE OF TRUTH for the
 * web assistant.
 *
 * Reads `../plugin/skills/<slug>/SKILL.md` (+ references/ + assets/) and emits
 * `web/lib/ai/skills.generated.ts`, embedding every skill body and reference as
 * a string constant. `systemPrompt.ts` assembles SYSTEM_PROMPT from the bodies;
 * the `get_skill_reference` action serves the references on demand.
 *
 * Why embed into a committed TS module (not read files at runtime): the web app
 * deploys only `web/`, and serverless has no reliable access to the repo-root
 * `plugin/` dir. Embedding keeps the web self-contained while the skills stay
 * the editable source — just re-run `npm run build:skills` after editing them.
 *
 * Run: `npm run build:skills`
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { dirname, join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SKILLS_DIR = join(HERE, '..', '..', 'plugin', 'skills');
const OUT = join(HERE, '..', 'lib', 'ai', 'skills.generated.ts');

/** Hub first, then spokes — the order they are inlined into SYSTEM_PROMPT. */
const ORDER = [
  'managing-clash-config',
  'synthesizing-proxy-groups',
  'editing-node-operators',
  'optimizing-whole-config',
];

function splitFrontmatter(text) {
  const m = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/.exec(text);
  if (!m) return { frontmatter: '', body: text.trim() };
  return { frontmatter: m[1], body: m[2].trim() };
}

function fieldName(fm) {
  const m = /^name:\s*(\S+)/m.exec(fm);
  return m ? m[1].trim() : '';
}

function fieldDescription(fm) {
  // block scalar `description: >-` followed by indented lines
  const block = /^description:\s*>-?\s*\n((?:[ \t]+.*\n?)+)/m.exec(fm);
  if (block) return block[1].split('\n').map((l) => l.trim()).filter(Boolean).join(' ');
  const inline = /^description:\s*(.+)$/m.exec(fm);
  return inline ? inline[1].trim() : '';
}

function readDirMd(dir) {
  if (!existsSync(dir) || !statSync(dir).isDirectory()) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .map((f) => ({ name: basename(f, '.md'), body: readFileSync(join(dir, f), 'utf8').trim() }));
}

const bodies = {};
const references = {};

for (const slug of ORDER) {
  const skillDir = join(SKILLS_DIR, slug);
  const skillFile = join(skillDir, 'SKILL.md');
  if (!existsSync(skillFile)) {
    console.error(`[build-skills] MISSING ${skillFile}`);
    process.exit(1);
  }
  const { frontmatter, body } = splitFrontmatter(readFileSync(skillFile, 'utf8'));
  bodies[slug] = { name: fieldName(frontmatter) || slug, description: fieldDescription(frontmatter), body };

  // references/ + assets/ → key `<slug>/<file>`
  for (const sub of ['references', 'assets']) {
    for (const ref of readDirMd(join(skillDir, sub))) {
      references[`${slug}/${ref.name}`] = ref.body;
    }
  }
}

const header = `// GENERATED by scripts/build-skills.mjs from ../plugin/skills — DO NOT EDIT BY HAND.
// Regenerate after editing any SKILL.md / reference: \`npm run build:skills\`.
// The plugin skills are the single source of truth; this module embeds them so
// the web app ships self-contained (no runtime access to the repo-root plugin/).

export interface SkillBody {
  name: string;
  description: string;
  body: string;
}

`;

const out =
  header +
  `export const SKILL_ORDER: readonly string[] = ${JSON.stringify(ORDER)};\n\n` +
  `export const SKILL_BODIES: Record<string, SkillBody> = ${JSON.stringify(bodies, null, 2)};\n\n` +
  `/** Reference / asset bodies keyed as \`<skill-slug>/<file-without-.md>\`. */\n` +
  `export const SKILL_REFERENCES: Record<string, string> = ${JSON.stringify(references, null, 2)};\n`;

writeFileSync(OUT, out);
console.error(
  `[build-skills] wrote ${OUT}\n  skills: ${ORDER.length}  references: ${Object.keys(references).length}`,
);
