import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { generateSkillsSource, loadSkills } from '../../scripts/build-skills.mjs';

/**
 * Round-1 canonical documentation contract (Architecture D):
 *   - plugin/skills/** is the editable truth; web/lib/ai/skills.generated.ts
 *     is generated-only — source-to-generated equality under the generator's
 *     REAL normalization (not a copied secondary truth, not a banned-word
 *     scan);
 *   - two builds produce identical bytes (deterministic generation);
 *   - the skill claims match the REGISTERED action schemas (semantic docs
 *     contract): profile-bound ref + source_type for source resolution,
 *     operator_handle for operator writes, node + to for rename_local_node,
 *     list_local_nodes output shape node/display/type/referencedBy.
 * Fictional illustrative node names (HK-01) are harmless and stay valid.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const GENERATED = join(HERE, '..', '..', 'lib', 'ai', 'skills.generated.ts');

describe('build-skills pure generator', () => {
  it('generated bytes equal the committed skills.generated.ts under the generator normalization', async () => {
    const generated = await generateSkillsSource();
    const committed = readFileSync(GENERATED, 'utf8');
    expect(generated).toBe(committed);
  });

  it('two builds produce identical bytes (deterministic)', async () => {
    const [a, b] = await Promise.all([generateSkillsSource(), generateSkillsSource()]);
    expect(a).toBe(b);
  });

  it('loadSkills covers the five canonical skills with references', () => {
    const { bodies, references, order } = loadSkills() as unknown as {
      bodies: Record<string, { name: string; body: string }>;
      references: Record<string, string>;
      order: string[];
    };
    expect(order).toEqual([
      'managing-clash-config',
      'synthesizing-proxy-groups',
      'editing-node-operators',
      'managing-devices',
      'optimizing-whole-config',
    ]);
    for (const slug of order) {
      expect(bodies[slug].name).toBeTruthy();
      expect(bodies[slug].body.length).toBeGreaterThan(0);
    }
    expect(Object.keys(references).length).toBeGreaterThan(10);
  });
});

describe('canonical docs match the registered action schemas (semantic contract)', () => {
  it('editing-node-operators documents the real input shapes: ref + source_type, operator_handle, node + to', async () => {
    const { bodies, references } = loadSkills() as unknown as {
      bodies: Record<string, { body: string }>;
      references: Record<string, string>;
    };
    const skill = bodies['editing-node-operators'].body;
    const kinds = references['editing-node-operators/operator-kinds'];
    const orphan = references['editing-node-operators/orphan-references'];
    // source resolution is ref-based — no raw source ids, no `from`-style
    // rename inputs
    expect(skill).toMatch(/`node` 句柄/);
    expect(skill).toMatch(/`rename_local_node` 用 `node` 句柄改某节点名/);
    expect(kinds).toMatch(/`ref` 与算子 handle/);
    expect(kinds).toMatch(/`operator_handle`/);
    expect(orphan).toMatch(/"display": "HK-01"/); // illustrative names stay valid
    // the list_local_nodes output shape claim matches the real action output
    expect(orphan).toMatch(/`node`，nd- 开头/);
    expect(orphan).toMatch(/`display`/);
    expect(orphan).toMatch(/`type`/);
    expect(orphan).toMatch(/`referencedBy`/);
  });

  it('tool-map describes list_local_nodes by its real output keys (node/display/type/referencedBy)', async () => {
    const { references } = loadSkills() as unknown as { references: Record<string, string> };
    const toolMap = references['managing-clash-config/tool-map'];
    expect(toolMap).toContain('node 句柄 + 有界脱敏显示名 display + type + referencedBy');
    expect(toolMap).toMatch(/`list_node_sources`/);
    expect(toolMap).toContain('profile-bound 不透明 ref');
  });

  it('no stale `from`-based rename or source-id input claims survive in the naming docs', async () => {
    const { references } = loadSkills() as unknown as { references: Record<string, string> };
    const toolMap = references['managing-clash-config/tool-map'];
    // the doc must never tell the model to pass a raw source id to a
    // source-bound tool
    expect(toolMap).not.toMatch(/source id 与不透明算子 handle/);
    const nodeSources = references['managing-clash-config/node-sources'];
    expect(nodeSources).toBeTruthy();
  });
});
