/**
 * GENERATED FILE — DO NOT EDIT.
 * Canonical receipt policy generated by web/scripts/generate-receipt-policy.mjs
 * from web/scripts/receipt-policy-spec.mjs. Manual spec + policy text live
 * ONLY in web/scripts/receipt-policy-spec.mjs; run the generator (or
 * `node web/scripts/generate-receipt-policy.mjs --check` to verify).
 */

export const RECEIPT_POLICY_VERSION = 1;
export const RECEIPT_POLICY_HASH =
  '4da3a08adcf972cd3fefac8ea6d3774fc09b498d2d4d8ce7626404929cbeb1c1';
export const RECEIPT_OP_RAW_MAX = 256;
export const RECEIPT_SUMMARY_RAW_MAX = 2048;
export const RECEIPT_OP_MAX = 64;
export const RECEIPT_SUMMARY_MAX = 512;

const RESIDUE_VOCABULARY = new Set<string>([
  'bearer',
  'basic',
  'token',
  'authorization',
  'api',
  'key',
  'sk',
  'uuid',
  'http',
  'https',
  'url',
  'redacted',
  'masked',
  'removed',
  'secret',
  'credential',
]);

/** Ordered semantic span regexes (compiled once at module load). */
const RECEIPT_SPANS = [
  /\b[a-z][a-z0-9+.-]*:\/\/[^\s"'<>]+/giu,
  /\[(?=[0-9a-f:.]*:)[0-9a-f:.]{1,64}(?:%[A-Za-z0-9._-]{1,32})?\](?::\d{1,5})?/giu,
  /\[[a-z0-9_-]{1,63}(?:\.[a-z0-9_-]{1,63})*\]:\d{1,5}/giu,
  /\b(?:[0-9a-f]{1,4}(?::[0-9a-f]{1,4}){0,6})?::(?:[0-9a-f]{1,4}(?::[0-9a-f]{1,4}){0,6})?(?:%[A-Za-z0-9._-]{1,32})?:\d{1,5}(?!\.\d)\b/giu,
  /\b[0-9a-f]{1,4}(?::[0-9a-f]{1,4}){1,7}:\d{1,5}(?!\.\d)\b/giu,
  /\b[0-9a-f]{1,4}(?::[0-9a-f]{1,4}){0,6}::(?:\d{1,3}(?:\.\d{1,3}){3}|[0-9a-f]{1,4}:\d{1,3}(?:\.\d{1,3}){3})(?::\d{1,5}(?!\.\d))?\b/giu,
  /(?<=^|[^0-9A-Za-z:])::(?:\d{1,3}(?:\.\d{1,3}){3}|[0-9a-f]{1,4}:\d{1,3}(?:\.\d{1,3}){3})(?::\d{1,5}(?!\.\d))?(?![0-9A-Za-z])/giu,
  /\b[0-9a-f]{1,4}(?::[0-9a-f]{1,4}){0,6}::(?![0-9A-Za-z])/giu,
  /\b[0-9a-f]{1,4}(?::[0-9a-f]{1,4}(?!\.\d)){0,6}::(?:[0-9a-f]{1,4}(?::[0-9a-f]{1,4}(?!\.\d)){0,6})\b/giu,
  /(?<=^|[^0-9A-Za-z:])(?:::[0-9a-f]{1,4}(?::[0-9a-f]{1,4}(?!\.\d)){0,6})(?::\d{1,3}(?:\.\d{1,3}){3})?(?![0-9A-Za-z])/giu,
  /\b(?:\d{1,3}\.){3}\d{1,3}:\d{1,5}(?!\.\d)\b/giu,
  /\b(?=[0-9a-f:]*[a-f])(?:[0-9a-f]{1,4}(?::[0-9a-f]{1,4}(?!\.\d)){1,7})\b/giu,
  /\b(?:[a-z0-9_](?:[a-z0-9_-]{0,61}[a-z0-9_])?\.)+(?:xn--[a-z0-9-]{2,20}|[a-z]{2,}):\d{1,5}(?!\.\d)\b/giu,
  /(?<![\p{L}\p{N}_])(?:[\p{L}\p{N}_]{1,63}\.)+(?:中国|香港|台湾|台灣|公司|网络|網絡|在线|在線|商城|网址|網址|商店|政务|政務|公益|集团|集團|游戏|遊戲|商标|商標|移动|移動|联通|聯通|中信|みんな|コム|世界|企业|企業|娱乐|娛樂|新闻|新聞|购物|購物):\d{1,5}(?!\.\d)(?![\p{L}\p{N}_])/giu,
  /\b[a-z][a-z0-9-]{0,31}:\d{1,5}(?!\.\d)\b/giu,
  /\b(?:\d{1,3}\.){3}\d{1,3}\b/giu,
  /%[A-Za-z][A-Za-z0-9._-]{0,31}/giu,
  /\b[A-Za-z0-9._%+-]{1,64}@(?:[a-z0-9_](?:[a-z0-9_-]{0,61}[a-z0-9_])?\.)+(?:xn--[a-z0-9-]{2,20}|[a-z]{2,})\b/giu,
  /(?<![\p{L}\p{N}_])[\p{L}\p{N}._%+-]{1,64}@(?:[\p{L}\p{N}_]{1,63}\.)+(?:中国|香港|台湾|台灣|公司|网络|網絡|在线|在線|商城|网址|網址|商店|政务|政務|公益|集团|集團|游戏|遊戲|商标|商標|移动|移動|联通|聯通|中信|みんな|コム|世界|企业|企業|娱乐|娛樂|新闻|新聞|购物|購物)(?![\p{L}\p{N}_])/giu,
  /\b(?:[a-z0-9_](?:[a-z0-9_-]{0,61}[a-z0-9_])?\.)+(?:xn--[a-z0-9-]{2,20}|[a-z]{2,})\b/giu,
  /(?<![\p{L}\p{N}_])(?:[\p{L}\p{N}_]{1,63}\.)+(?:中国|香港|台湾|台灣|公司|网络|網絡|在线|在線|商城|网址|網址|商店|政务|政務|公益|集团|集團|游戏|遊戲|商标|商標|移动|移動|联通|聯通|中信|みんな|コム|世界|企业|企業|娱乐|娛樂|新闻|新聞|购物|購物)(?![\p{L}\p{N}_])/giu,
  /(?:^|[^\p{L}\p{N}_-])(?:authorization\s*[:=]\s*)?(?:Bearer|Basic|Token)\s*[:=,;|(){}<>\[\]]\s*[^\s"'<>]*/gu,
  /(?:^|[^\p{L}\p{N}_-])(?:authorization\s*[:=]\s*)?(?:Bearer|Basic|Token)\s+[^\s"'<>]+(?=[\s,;(){}[\]]*(?:(?:(?:[bB][eE][aA][rR][eE][rR]|[bB][aA][sS][iI][cC]|[tT][oO][kK][eE][nN]|[pP][aA][sS][sS][wW][oO][rR][dD]|[pP][aA][sS][sS][wW][dD]|[pP][wW][dD]|[sS][eE][cC][rR][eE][tT]|[tT][oO][kK][eE][nN]|[aA][pP][iI]_[kK][eE][yY]|[aA][pP][iI]-[kK][eE][yY]|[aA][pP][iI][kK][eE][yY]|[aA][cC][cC][eE][sS][sS]_[kK][eE][yY]|[aA][cC][cC][eE][sS][sS]-[kK][eE][yY]|[aA][cC][cC][eE][sS][sS][kK][eE][yY]|[aA][uU][tT][hH]|[aA][uU][tT][hH][oO][rR][iI][zZ][aA][tT][iI][oO][nN]|[cC][rR][eE][dD][eE][nN][tT][iI][aA][lL]|[uU][uU][iI][dD]|[sS][nN][iI]|[hH][oO][sS][tT]|[kK][eE][yY]|[pP][sS][kK]|[cC][oO][dD][eE]|[sS][iI][gG][nN][aA][tT][uU][rR][eE]|[sS][iI][gG]|[oO][pP]|[cC][oO][oO][kK][iI][eE]|[cC][oO][oO][kK][iI][eE][sS]|[hH][eE][aA][dD][eE][rR]|[hH][eE][aA][dD][eE][rR][sS]|[pP][rR][iI][vV][aA][tT][eE]_[kK][eE][yY]|[pP][rR][iI][vV][aA][tT][eE]-[kK][eE][yY]|[pP][rR][iI][vV][aA][tT][eE][kK][eE][yY]|[sS][eE][sS][sS][iI][oO][nN]|[cC][sS][rR][fF]|[eE][nN][dD][pP][oO][iI][nN][tT]|[uU][rR][lL])\b|[sS][kK]-))|[\s,;(){}[\]]*$)/gu,
  /(?:^|[^\p{L}\p{N}_-])(?:authorization\s*[:=]\s*)?(?:Bearer|Basic|Token)(?=\s+(?:[bB][eE][aA][rR][eE][rR]|[bB][aA][sS][iI][cC]|[tT][oO][kK][eE][nN])\b|\s*$)/gu,
  /(?:^|[^\p{L}\p{N}_-])(?:authorization\s*[:=]\s*)?(?:BEARER|BASIC|TOKEN)\s*[:=,;|(){}<>\[\]]\s*[^\s"'<>]*/gu,
  /(?:^|[^\p{L}\p{N}_-])(?:authorization\s*[:=]\s*)?(?:BEARER|BASIC|TOKEN)\s+[^\s"'<>]+(?=[\s,;(){}[\]]*(?:(?:(?:[bB][eE][aA][rR][eE][rR]|[bB][aA][sS][iI][cC]|[tT][oO][kK][eE][nN]|[pP][aA][sS][sS][wW][oO][rR][dD]|[pP][aA][sS][sS][wW][dD]|[pP][wW][dD]|[sS][eE][cC][rR][eE][tT]|[tT][oO][kK][eE][nN]|[aA][pP][iI]_[kK][eE][yY]|[aA][pP][iI]-[kK][eE][yY]|[aA][pP][iI][kK][eE][yY]|[aA][cC][cC][eE][sS][sS]_[kK][eE][yY]|[aA][cC][cC][eE][sS][sS]-[kK][eE][yY]|[aA][cC][cC][eE][sS][sS][kK][eE][yY]|[aA][uU][tT][hH]|[aA][uU][tT][hH][oO][rR][iI][zZ][aA][tT][iI][oO][nN]|[cC][rR][eE][dD][eE][nN][tT][iI][aA][lL]|[uU][uU][iI][dD]|[sS][nN][iI]|[hH][oO][sS][tT]|[kK][eE][yY]|[pP][sS][kK]|[cC][oO][dD][eE]|[sS][iI][gG][nN][aA][tT][uU][rR][eE]|[sS][iI][gG]|[oO][pP]|[cC][oO][oO][kK][iI][eE]|[cC][oO][oO][kK][iI][eE][sS]|[hH][eE][aA][dD][eE][rR]|[hH][eE][aA][dD][eE][rR][sS]|[pP][rR][iI][vV][aA][tT][eE]_[kK][eE][yY]|[pP][rR][iI][vV][aA][tT][eE]-[kK][eE][yY]|[pP][rR][iI][vV][aA][tT][eE][kK][eE][yY]|[sS][eE][sS][sS][iI][oO][nN]|[cC][sS][rR][fF]|[eE][nN][dD][pP][oO][iI][nN][tT]|[uU][rR][lL])\b|[sS][kK]-))|[\s,;(){}[\]]*$)/gu,
  /(?:^|[^\p{L}\p{N}_-])(?:BEARER|BASIC|TOKEN)(?=\s+(?:[bB][eE][aA][rR][eE][rR]|[bB][aA][sS][iI][cC]|[tT][oO][kK][eE][nN])\b|\s*$)/gu,
  /(?:^|[^\p{L}\p{N}_-])sk-[A-Za-z0-9_-]*/giu,
  /\b[A-Za-z0-9_-]{6,}\.[A-Za-z0-9_-]{6,}\.[A-Za-z0-9_-]{6,}/giu,
  /\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/giu,
  /\b[0-9a-f]{16}\b/giu,
  /\b[0-9a-f]{32}\b/giu,
  /\b[A-Za-z0-9+/_-]{24,}\b/giu,
  /(?:^|[^\p{L}\p{N}_-])(?:password|passwd|pwd|secret|token|api_key|api-key|apikey|access_key|access-key|accesskey|auth|authorization|credential|uuid|sni|host|key|psk|code|signature|sig|op|cookie|cookies|header|headers|private_key|private-key|privatekey|session|csrf|endpoint|url)\s*[:=]\s*[^\s"'<>]*/giu,
  /(?:^|[^\p{L}\p{N}_-])(?:[pP][aA][sS][sS][wW][oO][rR][dD]|[pP][aA][sS][sS][wW][dD]|[pP][wW][dD]|[sS][eE][cC][rR][eE][tT]|[tT][oO][kK][eE][nN]|[aA][pP][iI]_[kK][eE][yY]|[aA][pP][iI]-[kK][eE][yY]|[aA][pP][iI][kK][eE][yY]|[aA][cC][cC][eE][sS][sS]_[kK][eE][yY]|[aA][cC][cC][eE][sS][sS]-[kK][eE][yY]|[aA][cC][cC][eE][sS][sS][kK][eE][yY]|[aA][uU][tT][hH]|[aA][uU][tT][hH][oO][rR][iI][zZ][aA][tT][iI][oO][nN]|[cC][rR][eE][dD][eE][nN][tT][iI][aA][lL]|[uU][uU][iI][dD]|[sS][nN][iI]|[hH][oO][sS][tT]|[kK][eE][yY]|[pP][sS][kK]|[cC][oO][dD][eE]|[sS][iI][gG][nN][aA][tT][uU][rR][eE]|[sS][iI][gG]|[oO][pP]|[cC][oO][oO][kK][iI][eE]|[cC][oO][oO][kK][iI][eE][sS]|[hH][eE][aA][dD][eE][rR]|[hH][eE][aA][dD][eE][rR][sS]|[pP][rR][iI][vV][aA][tT][eE]_[kK][eE][yY]|[pP][rR][iI][vV][aA][tT][eE]-[kK][eE][yY]|[pP][rR][iI][vV][aA][tT][eE][kK][eE][yY]|[sS][eE][sS][sS][iI][oO][nN]|[cC][sS][rR][fF]|[eE][nN][dD][pP][oO][iI][nN][tT]|[uU][rR][lL])\s+(?=[^\s"'<>]*[^a-z\s])[^\s"'<>]+(?=[\s,;(){}[\]]*(?:(?:(?:[bB][eE][aA][rR][eE][rR]|[bB][aA][sS][iI][cC]|[tT][oO][kK][eE][nN]|[pP][aA][sS][sS][wW][oO][rR][dD]|[pP][aA][sS][sS][wW][dD]|[pP][wW][dD]|[sS][eE][cC][rR][eE][tT]|[tT][oO][kK][eE][nN]|[aA][pP][iI]_[kK][eE][yY]|[aA][pP][iI]-[kK][eE][yY]|[aA][pP][iI][kK][eE][yY]|[aA][cC][cC][eE][sS][sS]_[kK][eE][yY]|[aA][cC][cC][eE][sS][sS]-[kK][eE][yY]|[aA][cC][cC][eE][sS][sS][kK][eE][yY]|[aA][uU][tT][hH]|[aA][uU][tT][hH][oO][rR][iI][zZ][aA][tT][iI][oO][nN]|[cC][rR][eE][dD][eE][nN][tT][iI][aA][lL]|[uU][uU][iI][dD]|[sS][nN][iI]|[hH][oO][sS][tT]|[kK][eE][yY]|[pP][sS][kK]|[cC][oO][dD][eE]|[sS][iI][gG][nN][aA][tT][uU][rR][eE]|[sS][iI][gG]|[oO][pP]|[cC][oO][oO][kK][iI][eE]|[cC][oO][oO][kK][iI][eE][sS]|[hH][eE][aA][dD][eE][rR]|[hH][eE][aA][dD][eE][rR][sS]|[pP][rR][iI][vV][aA][tT][eE]_[kK][eE][yY]|[pP][rR][iI][vV][aA][tT][eE]-[kK][eE][yY]|[pP][rR][iI][vV][aA][tT][eE][kK][eE][yY]|[sS][eE][sS][sS][iI][oO][nN]|[cC][sS][rR][fF]|[eE][nN][dD][pP][oO][iI][nN][tT]|[uU][rR][lL])\b|[sS][kK]-))|[\s,;(){}[\]]*$)/gu,
  /(?:^|[^\p{L}\p{N}_-])(?:password|passwd|pwd|secret|token|api_key|api-key|apikey|access_key|access-key|accesskey|auth|authorization|credential|uuid|sni|host|key|psk|code|signature|sig|op|cookie|cookies|header|headers|private_key|private-key|privatekey|session|csrf|endpoint|url)(?=\s*$)/giu,
  /\b(?:redacted|masked|removed)\b|\[(?:redacted|masked|removed)\]/giu,
  /[?&][A-Za-z0-9._-]{1,64}=[^&\s"'<>]{0,128}/giu,
  /(?:^|\s)[A-Za-z0-9._-]{1,64}=[^&\s"'<>]{0,128}/giu,
];
const RECEIPT_SPAN_NAMES: string[] = [
  'url',
  'endpoint-bracketed-ipv6',
  'endpoint-bracketed-host-port',
  'endpoint-ipv6-compressed-port',
  'endpoint-ipv6-full-port',
  'endpoint-ipv6-mapped',
  'endpoint-ipv6-mapped-leading',
  'endpoint-ipv6-trailing-cc',
  'endpoint-ipv6-compressed-tail',
  'endpoint-ipv6-omitted',
  'endpoint-ipv4-port',
  'endpoint-ipv6-full-hextet',
  'endpoint-hostname-port',
  'endpoint-hostname-port-cjk',
  'endpoint-single-label-port',
  'endpoint-ipv4',
  'endpoint-zone',
  'email',
  'email-cjk',
  'hostname',
  'hostname-cjk',
  'scheme-attached',
  'scheme-payload',
  'scheme-bare',
  'scheme-attached-caps',
  'scheme-payload-caps',
  'scheme-bare-caps',
  'sk-prefix',
  'jwt',
  'uuid',
  'hex16',
  'hex32',
  'opaque24',
  'key-delim',
  'key-payload',
  'key-bare',
  'placeholder',
  'query',
  'query-generic',
];
/** Span names skipped when canonicalizing in op context (length-based
 * opaque classification must never erase a valid long lower-kebab op). */
const OP_CONTEXT_SKIP = new Set<string>(['opaque24']);

/** Every Unicode Cc/Cf code point becomes ONE nonjoining separator. */
export function replaceReceiptControls(value: string): string {
  return value.replace(/\p{Cc}|\p{Cf}/gu, ' ');
}

/** Remove every semantic sensitive span; each span becomes ONE space. */
export function removeReceiptSpans(value: string, opContext: boolean): string {
  let out = value;
  for (let i = 0; i < RECEIPT_SPANS.length; i += 1) {
    if (opContext && OP_CONTEXT_SKIP.has(RECEIPT_SPAN_NAMES[i])) continue;
    out = out.replace(RECEIPT_SPANS[i], ' ');
  }
  return out;
}

/**
 * True when the text contains at least one Unicode letter-or-number token
 * that is NOT a residue-vocabulary word (case-folded).
 */
export function hasMeaningfulResidue(value: string): boolean {
  const tokens = value.split(/[^\p{L}\p{N}]+/u).filter((token) => token !== '');
  return tokens.some((token) => {
    if (!/[\p{L}\p{N}]/u.test(token)) return false;
    return !RESIDUE_VOCABULARY.has(token.toLocaleLowerCase('en'));
  });
}

/**
 * Web producer canonicalization: raw UTF-16 bound BEFORE any normalization
 * (never slice), NFKC, Cc/Cf separators, ordered span removal, whitespace
 * collapse, then the meaningful-residue rule. Returns null when nothing
 * safe and meaningful remains — the caller yields the fixed unknown.
 * opContext skips the opaque-24 span so a valid long lower-kebab op is
 * never classified opaque merely by length.
 */
export function canonicalizeReceiptText(
  raw: unknown,
  rawBound: number,
  opContext?: boolean,
): string | null {
  if (typeof raw !== 'string') return null;
  if (raw.length > rawBound) return null;
  let cleaned = raw.normalize('NFKC');
  cleaned = replaceReceiptControls(cleaned);
  cleaned = removeReceiptSpans(cleaned, opContext === true);
  cleaned = cleaned.replace(/\s+/g, ' ').trim();
  if (cleaned === '') return null;
  if (!hasMeaningfulResidue(cleaned)) return null;
  return cleaned;
}

/**
 * MCP verifier check: the summary must ALREADY be canonical — NFKC identity,
 * no Cc/Cf controls, no span removal, no whitespace collapse, meaningful
 * residue, and within the raw + canonical bounds.
 */
export function isCanonicalReceiptSummary(summary: unknown): boolean {
  if (typeof summary !== 'string' || summary === '') return false;
  if (summary.length > RECEIPT_SUMMARY_RAW_MAX) return false;
  if (summary.length > RECEIPT_SUMMARY_MAX) return false;
  if (summary.normalize('NFKC') !== summary) return false;
  const withSeparators = replaceReceiptControls(summary);
  if (withSeparators !== summary) return false;
  const afterSpans = removeReceiptSpans(withSeparators, false);
  if (afterSpans !== summary) return false;
  const collapsed = afterSpans.replace(/\s+/g, ' ').trim();
  if (collapsed !== afterSpans) return false;
  return hasMeaningfulResidue(collapsed);
}
